// Generated by CoffeeScript 1.12.2
(function() {
  var makePromise;

  makePromise = require("./make-promise");

  module.exports = {
    pending: function() {
      var pending;
      pending = {};
      pending.promise = makePromise(function(cb) {
        pending.fulfill = function(value) {
          return cb(null, value);
        };
        return pending.reject = function(error) {
          return cb(error, null, true);
        };
      });
      return pending;
    },
    resolved: function(value) {
      return makePromise(function(cb) {
        return cb(null, value);
      });
    },
    rejected: function(value) {
      return makePromise(function(cb) {
        return cb(value, null, true);
      });
    },
    deferred: function() {
      var pending;
      pending = {};
      pending.promise = makePromise(function(cb) {
        pending.resolve = function(value) {
          return cb(null, value);
        };
        return pending.reject = function(reason) {
          return cb(reason, null, true);
        };
      });
      return pending;
    }
  };

}).call(this);

//# sourceMappingURL=adapter.js.map
