// Generated by CoffeeScript 1.12.2
(function() {
  var Promise, makePromise;

  Promise = require("bluebird");

  module.exports = makePromise = function(fn) {
    var promise, rejectPromise, resolvePromise;
    resolvePromise = void 0;
    rejectPromise = void 0;
    return promise = new Promise(function(resolve, reject) {
      var cb, error;
      resolvePromise = resolve;
      rejectPromise = reject;
      cb = function(err, result, forceError) {
        if (forceError == null) {
          forceError = false;
        }
        if ((err != null) || forceError) {
          return rejectPromise(err);
        } else {
          return resolvePromise(result);
        }
      };
      try {
        return fn(cb);
      } catch (error1) {
        error = error1;
        return cb(error, null, true);
      }
    });
  };

}).call(this);

//# sourceMappingURL=make-promise.js.map
